/**
 * Theme templates owned by D&VFly.
 *
 * "Mostrar cabeçalho e rodapé" is not a CSS trick: the theme's header and
 * footer live in its layout, so the only honest way to remove them is to bind
 * the page to a different layout. Publishing writes three small files into the
 * store's MAIN theme — a minimal layout, a section that renders the page body,
 * and a page template pointing at both — and then points the page at that
 * template via `templateSuffix`.
 *
 * Everything here is idempotent: the files are upserted with fixed names and
 * identical content on every publish, so re-publishing changes nothing. The
 * layout keeps `content_for_header` — Shopify's own scripts (analytics,
 * consent, payments) must survive losing the theme chrome.
 *
 * Proven live on 15/09/2026: a page bound to `page.dvfly-solo` renders on the
 * storefront with no theme header/footer and with Shopify's head intact.
 */

import { ShopifyError, type ShopifyClient } from './client.ts';
import { SOLO_SUFFIX } from './constants.ts';

export { SOLO_SUFFIX };

const LAYOUT_FILE = 'layout/theme.dvfly.liquid';
const SECTION_FILE = 'sections/dvfly-page.liquid';
const TEMPLATE_FILE = `templates/page.${SOLO_SUFFIX}.json`;

const LAYOUT = `<!doctype html>
<html lang="{{ request.locale.iso_code }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="canonical" href="{{ canonical_url }}">
  <title>{{ page_title }}</title>
  {{ content_for_header }}
</head>
<body style="margin:0">
  {{ content_for_layout }}
</body>
</html>
`;

const SECTION = `{{ page.content }}
{% schema %}
{ "name": "Pagina DVFly", "settings": [] }
{% endschema %}
`;

const TEMPLATE = JSON.stringify(
  {
    layout: 'theme.dvfly',
    sections: { main: { type: 'dvfly-page' } },
    order: ['main'],
  },
  null,
  2,
);

// ---- product pages: one template per page ---------------------------------

/** The templateSuffix a product page gets, derived from the page id. */
export const productSuffix = (pageId: string) => `dvfly-${pageId.toLowerCase()}`;
/** The section (file stem) that carries the page's compiled content. */
export const productSectionType = (pageId: string) => `dvfly-p-${pageId.toLowerCase()}`;

const productTemplateFile = (pageId: string) => `templates/product.${productSuffix(pageId)}.json`;
const productSectionFile = (pageId: string) => `sections/${productSectionType(pageId)}.liquid`;

/** Theme JSON files start with a comment block the editor writes; JSON.parse does not accept it. */
export function stripJsonComments(text: string): string {
  return text.replace(/^\s*\/\*[\s\S]*?\*\/\s*/, '');
}

/** Reads one theme file as text, or null when the theme does not have it. */
export async function readThemeFile(
  client: ShopifyClient,
  themeId: string,
  filename: string,
): Promise<string | null> {
  const data = await client.graphql<{
    theme: {
      files: { nodes: Array<{ filename: string; body: { content?: string } }> };
    } | null;
  }>(
    `query DvflyThemeFile($themeId: ID!, $filenames: [String!]!) {
       theme(id: $themeId) {
         files(filenames: $filenames, first: 1) {
           nodes { filename body { ... on OnlineStoreThemeFileBodyText { content } } }
         }
       }
     }`,
    { themeId, filenames: [filename] },
  );
  const node = data.theme?.files.nodes.find((f) => f.filename === filename);
  return node?.body.content ?? null;
}

export interface ProductTemplateInput {
  pageId: string;
  /** Shown in the theme editor as the section's name. */
  title: string;
  /** The compiled fragment: <style> + markup + optional <script>. */
  fragment: string;
  /** Our content above the theme's product sections instead of below. */
  contentAbove?: boolean;
}

/**
 * Renders the section file: the compiled page verbatim, plus the schema the
 * theme editor needs. `{% raw %}` keeps the author's HTML out of Liquid's
 * hands — a `{{` in pasted markup must reach the browser as text.
 */
export function productSectionLiquid(input: ProductTemplateInput): string {
  if (/\{%-?\s*endraw\s*-?%\}/i.test(input.fragment)) {
    throw new ShopifyError(
      'O conteúdo da página contém "{% endraw %}", que a Shopify não permite dentro de uma seção.',
    );
  }
  // Section names are capped at 25 characters by the theme editor.
  const name = `D&VFly · ${input.title}`.slice(0, 25);
  return [
    `{%- comment -%} Generated by D&VFly for page ${input.pageId}. Edit the page in D&VFly, not here. {%- endcomment -%}`,
    '{% raw %}',
    input.fragment,
    '{% endraw %}',
    '{% schema %}',
    JSON.stringify({ name, settings: [] }),
    '{% endschema %}',
    '',
  ].join('\n');
}

/**
 * Composes our template from the theme's own `templates/product.json`: every
 * section the theme renders on a product page stays (price, variants, buy),
 * and ours is added below them — or above, when asked. The merchant can still
 * reorder or hide any of them in the theme editor.
 */
export function composeProductTemplate(
  themeProductJson: string | null,
  input: ProductTemplateInput,
): string {
  let base: { sections?: Record<string, unknown>; order?: string[]; [key: string]: unknown } = {};
  if (themeProductJson) {
    try {
      base = JSON.parse(stripJsonComments(themeProductJson));
    } catch {
      throw new ShopifyError('O templates/product.json do tema não pôde ser lido como JSON.');
    }
  }
  const sections = { ...(base.sections ?? {}) };
  const order = [...(base.order ?? [])].filter((id) => id in sections);
  if (order.length === 0) {
    throw new ShopifyError(
      'O tema não tem um templates/product.json com seções — não dá para compor o modelo de produto.',
    );
  }
  const ours = 'dvfly';
  sections[ours] = { type: productSectionType(input.pageId), settings: {} };
  const composed = {
    ...base,
    sections,
    order: input.contentAbove ? [ours, ...order] : [...order, ours],
  };
  return JSON.stringify(composed, null, 2);
}

/**
 * Writes (or rewrites) the page's product template and section into the main
 * theme. Idempotent by content. Returns the suffix products must be pointed at.
 */
export async function ensureProductTemplate(
  client: ShopifyClient,
  input: ProductTemplateInput,
): Promise<{ suffix: string; files: string[] }> {
  const themeId = await mainThemeId(client);
  const themeProduct = await readThemeFile(client, themeId, 'templates/product.json');
  const files = [
    { filename: productSectionFile(input.pageId), body: { type: 'TEXT', value: productSectionLiquid(input) } },
    { filename: productTemplateFile(input.pageId), body: { type: 'TEXT', value: composeProductTemplate(themeProduct, input) } },
  ];
  await upsertThemeFiles(client, themeId, files);
  return { suffix: productSuffix(input.pageId), files: files.map((f) => f.filename) };
}

/** Removes the page's template and section from the main theme. */
export async function removeProductTemplate(client: ShopifyClient, pageId: string): Promise<void> {
  const themeId = await mainThemeId(client);
  const data = await client.graphql<{
    themeFilesDelete: { deletedThemeFiles: Array<{ filename: string }> | null; userErrors: unknown[] };
  }>(
    `mutation DvflyThemeFilesDelete($themeId: ID!, $files: [String!]!) {
       themeFilesDelete(themeId: $themeId, files: $files) {
         deletedThemeFiles { filename }
         userErrors { field message }
       }
     }`,
    { themeId, files: [productTemplateFile(pageId), productSectionFile(pageId)] },
  );
  const errors = data.themeFilesDelete.userErrors;
  // A file that is already gone is not a failure.
  if (errors.length > 0 && !/not found|does not exist/i.test(JSON.stringify(errors))) {
    throw new ShopifyError(
      `Não foi possível remover o modelo de produto do tema de ${client.domain}: ${JSON.stringify(errors)}`,
      { userErrors: errors },
    );
  }
}

async function upsertThemeFiles(
  client: ShopifyClient,
  themeId: string,
  files: Array<{ filename: string; body: { type: string; value: string } }>,
): Promise<void> {
  const data = await client.graphql<{
    themeFilesUpsert: {
      upsertedThemeFiles: Array<{ filename: string }> | null;
      userErrors: unknown[];
    };
  }>(
    `mutation DvflyThemeFiles($themeId: ID!, $files: [OnlineStoreThemeFilesUpsertFileInput!]!) {
       themeFilesUpsert(themeId: $themeId, files: $files) {
         upsertedThemeFiles { filename }
         userErrors { field message }
       }
     }`,
    { themeId, files },
  );
  const { upsertedThemeFiles, userErrors } = data.themeFilesUpsert;
  if (!upsertedThemeFiles || upsertedThemeFiles.length !== files.length) {
    throw new ShopifyError(
      `Não foi possível gravar arquivos no tema de ${client.domain}: ${JSON.stringify(userErrors)}`,
      { userErrors },
    );
  }
}

/** The store's MAIN theme — the one visitors see. */
export async function mainThemeId(client: ShopifyClient): Promise<string> {
  const data = await client.graphql<{ themes: { nodes: Array<{ id: string }> } }>(
    `{ themes(first: 1, roles: [MAIN]) { nodes { id } } }`,
  );
  const theme = data.themes.nodes[0];
  if (!theme) {
    throw new ShopifyError(`A loja ${client.domain} não tem tema principal publicado.`);
  }
  return theme.id;
}

/**
 * Writes (or rewrites) the chrome-less page template into the main theme.
 * Safe to call on every publish.
 */
export async function ensureSoloTemplate(client: ShopifyClient): Promise<void> {
  const themeId = await mainThemeId(client);
  await upsertThemeFiles(client, themeId, [
    { filename: LAYOUT_FILE, body: { type: 'TEXT', value: LAYOUT } },
    { filename: SECTION_FILE, body: { type: 'TEXT', value: SECTION } },
    { filename: TEMPLATE_FILE, body: { type: 'TEXT', value: TEMPLATE } },
  ]);
}
